### ISSUE TITLE
Svelte

### ISSUE THREAD

**Issue by 7heMech** [abielzulio/supabase-desktop#8]
Maybe you could switch to Svelte for better performance?
If I made a PR trying to do that would you accept?

**Comment by gelove** [comment]
This project has no frontend code...

**Comment by 7heMech** [comment]
> This project has no frontend code...

It uses react and tsx though

**Comment by gelove** [comment]
```
import React from 'react';
import ReactDOM from 'react-dom/client';
import './style.css';

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <div />
  </React.StrictMode>
);
```
All react code...
This project is just a supabasee web wrapper.
